# Arguments for training-----------------------------------
train_config:
  dataset_root: C:/Users/yangc/Developer/data/casia-webface # root directory of dataset
  datalist: C:/Users/yangc/Developer/data/casia-webface-list.txt # dataset explanation file
  dataset: casia-webface # dataset name
  num_workers: 4 # number of workers in DataLoader
  pin_memory: True # use pin_memory in DataLoader if your memory is big enough

  device: gpu # cpu, gpu
  backbone: iresnet18 # backbone network for face feature extraction

  # training parameters
  num_epochs: 50 # number of epochs
  batch_size: 100
  lr: 0.1
  lr_gamma: 0.1 # decay rate of learning rate
  step_size: 5 # decay learning rate every step_size epochs
  weight_decay: 5e-4 

  metric: arcface # metric function
  loss: focal_loss # focal_loss, cross_entropy
  gamma: 2 # parameter for focal loss
  optimizer: sgd # sgd, adam

  resume: True # False, True
  resume_file: checkpoint_arcface_iresnet18_27.pth # resume from a specific epoch

  save_all_states: True # False, True
  save_dir: C:/Users/yangc/Developer/Face-Recognition/saves # directory to save checkpoints and trained models

  show_progress: True # False, True

# Arguments for evaluating-----------------------------------
eval_config:
  dataset_root: C:/Users/yangc/Developer/data/lfw-aligned # root directory of dataset
  datalist: data/lfw-list.txt # dataset explanation file
  dataset: lfw # dataset name
  num_workers: 0 # number of workers in DataLoader
  pin_memory: True # use pin_memory in DataLoader if your memory is big enough

  model_path: C:/Users/yangc/Developer/Face-Recognition/saves/checkpoint_arcface_iresnet18_33.pth # path to the trained model
  device: gpu # cpu, gpu
  backbone: iresnet18 # backbone network for face feature extraction
  batch_size: 100

  show_progress: True # False, True